closes #9: configuring topic subscription with config properties
NovatecConsulting/micronaut-camunda-external-client pull request #16
Opened 2021-04-23 04:48 UTC by lwluc

2021-04-23 08:18 UTC, martisaw commented on README.md
> +      my-topic:
I think "my-topic" should match the handler provided below ("test-topic-configuration")

2021-04-23 08:26 UTC, tobiasschaefer reviewed
@lwluc thanks. I started with the review thinking Martin had already had a look at the PR. I just heard that he is still reviewing.
I'm submitting my current comments and I'll finish my review when you've incorporated all comments from Martin.

2021-05-11 18:01 UTC, tobiasschaefer requested changes
@martisaw : thanks - I added some comments. Let's talk once you had a look at them.

2021-05-17 19:44 UTC, tobiasschaefer approved these changes

2021-05-17 19:44 UTC, merged